name: lexiverse
description: "Learn Through Your Eyes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-176.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0+1
  cupertino_icons: ^1.0.8
  flutter_chat_bubble: ^2.0.2
  flutter_image_compress: ^2.3.0
  flutter_markdown: ^0.7.1
  image_picker: ^1.1.2
  isar_flutter_libs: ^4.0.0-dev.13
  flutter_riverpod: ^3.0.0-dev.3
  freezed_annotation: ^2.4.1
  google_generative_ai: ^0.4.2
  hive: ^4.0.0-dev.2
  mesh_gradient: ^1.3.7
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  riverpod_annotation: ^3.0.0-dev.3
  json_annotation: ^4.9.0
  skeletonizer: ^1.4.2
  shimmer: ^3.0.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  riverpod_generator: ^3.0.0-dev.11
  freezed: ^2.5.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/goat.jpg

analyzer:
  errors:
    invalid_annotation_target: ignore